version: "3.9"

services:
  db_booking:
    container_name: ms_booking_db
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking123

  ms-identity:
    container_name: ms_booking_app
    image: ms-booking-app:1.0
    ports:
      - "8081:8081"
    restart: unless-stopped
    build:
      context: ms-booking
      dockerfile: Dockerfile
    depends_on:
      - db_booking
    network_mode: "host"