version: "3.9"

services:
  postgres:
    image: 'postgres:latest'
    container_name: ms-booking.db
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    networks:
      - booking
  app:
    build:
      context: .
    container_name: ms_booking.app
    depends_on:
      - postgres
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - booking

#volumes:
#  postgres_data:

networks:
  booking: