services:
  db_booking:
    container_name: ms_booking_db
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking123

  ms-booking:
    container_name: ms_booking_app
    ports:
      - "8080:8080"
#    restart: unless-stopped
    build:
      dockerfile: Dockerfile
    depends_on:
      - db_booking