spring:
  application:
    name: ms-booking
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
  datasource:
    url: jdbc:postgresql://localhost:5433/booking
    username: booking
    password: booking123
